server:
  port: 8080
spring:
  application:
    name: spring-batch-processing-film

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false

app4ang:
  file:
    input-file-name: "classpath:/film.csv"
    header-names: "Year; Length; Title; Subject; Actor; Actress; Director; Popularity; Awards; Image"
    delimiter: ";"



